services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --config gunicorn.conf.py"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8080:8080"
    environment:
      - DEBUG=True
      - PORT=8080
    env_file:
      - ./.env

volumes:
  static_volume: