name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker authentication
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Build and Push Docker image
      env:
        GCP_PROJECT: golden-bonbon-449702-p6
        IMAGE: asia-south1-docker.pkg.dev/golden-bonbon-449702-p6/cloud-run-source-deploy/kaloforge
      run: |
        docker build \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
          --build-arg DEBUG=${{ secrets.DEBUG }} \
          --build-arg API_KEY=${{ secrets.API_KEY }} \
          --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
          --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
          -t ${IMAGE}:${{ github.sha }} .
        docker push ${IMAGE}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy kaloforge \
          --image asia-south1-docker.pkg.dev/golden-bonbon-449702-p6/cloud-run-source-deploy/kaloforge:${{ github.sha }} \
          --platform managed \
          --region asia-east1 \
          --project golden-bonbon-449702-p6 \
          --allow-unauthenticated \
          --port 8080 \
          --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }},SECRET_KEY=${{ secrets.SECRET_KEY }},DEBUG=${{ secrets.DEBUG }},API_KEY=${{ secrets.API_KEY }},AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }},AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }},GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"